"""
Django settings for fashion_store project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote


# Build paths inside the project like this:
# BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings
# https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = (
    "django-insecure-"
    "vl2&3^0&kwpca_&0@7rr(!0ypaq8w^jfm*72n@%8+s#+me3d(x"
)

DEBUG = os.getenv(
    "DJANGO_DEBUG",
    "False",
).lower() == "true"


# Kubernetes supplies DJANGO_ALLOWED_HOSTS as a comma-separated
# string. Django requires ALLOWED_HOSTS to be a Python list.

allowed_hosts_value = os.getenv(
    "DJANGO_ALLOWED_HOSTS",
    (
        "192.168.1.25,"
        "127.0.0.1,"
        "192.168.1.240,"
        "fashion.local,"
        "localhost"
    ),
)

ALLOWED_HOSTS = [
    host.strip()
    for host in allowed_hosts_value.split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "catalog.apps.CatalogConfig",
    "accounts",
    "discovery",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fashion_store.urls"

TEMPLATES = [
    {
        "BACKEND": (
            "django.template.backends.django."
            "DjangoTemplates"
        ),
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                (
                    "django.template.context_processors."
                    "request"
                ),
                (
                    "django.contrib.auth."
                    "context_processors.auth"
                ),
                (
                    "django.contrib.messages."
                    "context_processors.messages"
                ),
            ],
        },
    },
]

WSGI_APPLICATION = "fashion_store.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ["POSTGRES_DB"],
        "USER": os.environ["POSTGRES_USER"],
        "PASSWORD": os.environ["POSTGRES_PASSWORD"],
        "HOST": os.environ.get(
            "POSTGRES_HOST",
            "postgres",
        ),
        "PORT": os.environ.get(
            "POSTGRES_PORT",
            "5432",
        ),
        "CONN_MAX_AGE": 60,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": (
            "django.core.files.storage."
            "FileSystemStorage"
        ),
    },
    "staticfiles": {
        "BACKEND": (
            "whitenoise.storage."
            "CompressedManifestStaticFilesStorage"
        ),
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CSRF and reverse-proxy configuration

csrf_trusted_origins_value = os.getenv(
    "DJANGO_CSRF_TRUSTED_ORIGINS",
    "",
)

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in csrf_trusted_origins_value.split(",")
    if origin.strip()
]

SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


# Authentication redirects

LOGIN_URL = "/account/login/"
LOGIN_REDIRECT_URL = "/account/"
LOGOUT_REDIRECT_URL = "/"


# Redis cache configuration

REDIS_HOST = os.getenv(
    "REDIS_HOST",
    "redis",
)

REDIS_PORT = os.getenv(
    "REDIS_PORT",
    "6379",
)

REDIS_DB = os.getenv(
    "REDIS_DB",
    "1",
)

REDIS_PASSWORD = os.environ["REDIS_PASSWORD"]

CACHES = {
    "default": {
        "BACKEND": (
            "django_redis.cache.RedisCache"
        ),
        "LOCATION": (
            f"redis://{REDIS_HOST}:"
            f"{REDIS_PORT}/{REDIS_DB}"
        ),
        "OPTIONS": {
            "CLIENT_CLASS": (
                "django_redis.client.DefaultClient"
            ),
            "PASSWORD": REDIS_PASSWORD,
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
            "RETRY_ON_TIMEOUT": True,
        },
        "KEY_PREFIX": "vastra",
        "TIMEOUT": 300,
    },
}


# Store sessions in both Redis and PostgreSQL.
# PostgreSQL provides recovery if Redis is restarted.

SESSION_ENGINE = (
    "django.contrib.sessions.backends.cached_db"
)

SESSION_CACHE_ALIAS = "default"


# RabbitMQ and Celery configuration

RABBITMQ_USER = os.environ["RABBITMQ_USER"]
RABBITMQ_PASSWORD = os.environ["RABBITMQ_PASSWORD"]

RABBITMQ_HOST = os.environ.get(
    "RABBITMQ_HOST",
    "rabbitmq",
)

RABBITMQ_PORT = os.environ.get(
    "RABBITMQ_PORT",
    "5672",
)

RABBITMQ_VHOST = os.environ.get(
    "RABBITMQ_VHOST",
    "vastra",
)

rabbitmq_user_encoded = quote(
    RABBITMQ_USER,
    safe="",
)

rabbitmq_password_encoded = quote(
    RABBITMQ_PASSWORD,
    safe="",
)

rabbitmq_vhost_encoded = quote(
    RABBITMQ_VHOST,
    safe="",
)

CELERY_BROKER_URL = (
    f"amqp://"
    f"{rabbitmq_user_encoded}:"
    f"{rabbitmq_password_encoded}@"
    f"{RABBITMQ_HOST}:"
    f"{RABBITMQ_PORT}/"
    f"{rabbitmq_vhost_encoded}"
)

celery_redis_password = quote(
    REDIS_PASSWORD,
    safe="",
)

celery_redis_db = os.environ.get(
    "CELERY_REDIS_DB",
    "2",
)

CELERY_RESULT_BACKEND = (
    f"redis://:"
    f"{celery_redis_password}@"
    f"{REDIS_HOST}:"
    f"{REDIS_PORT}/"
    f"{celery_redis_db}"
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_ENABLE_UTC = True

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_TASK_TRACK_STARTED = True
CELERY_RESULT_EXPIRES = 3600

CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True

SUPABASE_URL = os.getenv(
    "SUPABASE_URL",
    "",
).strip().rstrip("/")

SUPABASE_PUBLISHABLE_KEY = os.getenv(
    "SUPABASE_PUBLISHABLE_KEY",
    "",
).strip()
