# Generated by Django 5.2.17 on 2026-10-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='supabase_user_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
