# Generated by Django 5.2.17 on 2026-09-30 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0005_backfill_commerce_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('website_url', models.URLField(max_length=1000)),
                ('search_url_template', models.CharField(blank=True, help_text='Use {query} where the encoded customer search should be inserted.', max_length=1000)),
                ('channel', models.CharField(choices=[('ONLINE', 'Online'), ('PHYSICAL', 'Physical stores'), ('BOTH', 'Online and physical')], default='ONLINE', max_length=20)),
                ('integration_level', models.CharField(choices=[('LINK_ONLY', 'External link only'), ('DEMO', 'Development demo'), ('MANUAL_FEED', 'Manual catalogue feed'), ('AFFILIATE_FEED', 'Affiliate catalogue feed'), ('LIVE_API', 'Live retailer API'), ('CHECKOUT_API', 'Integrated checkout API')], default='LINK_ONLY', max_length=30)),
                ('is_demo', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supported_categories', models.ManyToManyField(blank=True, related_name='retailers', to='catalog.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=12)),
                ('map_url', models.URLField(blank=True, max_length=1000)),
                ('is_demo', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_locations', to='discovery.retailer')),
            ],
            options={
                'ordering': ['retailer__name', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RetailerOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_sku', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('product_url', models.URLField(max_length=2000)),
                ('image_url', models.URLField(blank=True, max_length=2000)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_sizes', models.JSONField(blank=True, default=list)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(choices=[('IN_STOCK', 'In stock'), ('OUT_OF_STOCK', 'Out of stock'), ('CHECK_RETAILER', 'Check with retailer'), ('UNKNOWN', 'Unknown')], default='CHECK_RETAILER', max_length=30)),
                ('fulfilment', models.CharField(choices=[('ONLINE', 'Online'), ('STORE', 'Physical store'), ('BOTH', 'Online or store')], default='ONLINE', max_length=20)),
                ('is_demo', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retailer_offers', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_offers', to='catalog.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='discovery.retailer')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_offers', to='catalog.productvariant')),
                ('store_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='discovery.storelocation')),
            ],
            options={
                'ordering': ['price', 'retailer__name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DemandRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('original_query', models.TextField()),
                ('parsed_intent', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('MATCHED', 'Exact match found'), ('PARTIAL', 'Partial match found'), ('UNMATCHED', 'No match found')], default='UNMATCHED', max_length=20)),
                ('internal_match_count', models.PositiveIntegerField(default=0)),
                ('retailer_match_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='demand_status_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='storelocation',
            constraint=models.UniqueConstraint(fields=('retailer', 'name', 'postal_code'), name='uniq_store_name_pin'),
        ),
        migrations.AddIndex(
            model_name='retaileroffer',
            index=models.Index(fields=['retailer', 'is_active'], name='offer_retailer_active_idx'),
        ),
        migrations.AddIndex(
            model_name='retaileroffer',
            index=models.Index(fields=['category', 'is_active'], name='offer_category_active_idx'),
        ),
    ]
