apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fashion-store

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - redis.yaml
  - rabbitmq.yaml

images:
  - name: registry.local:5000/vastra/fashion-store
    newTag: sha-45275ee6dabc
